on: [push]

jobs:
  nixfmt-check:
    runs-on: native
    env:
      GIT_SSL_NO_VERIFY: true
    steps:
      - name: Checkout code via SSH
        uses: actions/checkout@v4
      - name: Run nix format check
        run: alejandra --check .
