{
  config,
  inputs,
  ...
}: let
  c = config.theme.colors;
  dmsSettings = builtins.fromJSON ''
    {
      "currentThemeName": "custom",
      "currentThemeCategory": "custom",
      "customThemeFile": "/home/uday/.config/DankMaterialShell/themes/stylix/theme.json",
      "enableDynamicTheming": false,
      "registryThemeVariants": {},
      "matugenScheme": "scheme-tonal-spot",
      "matugenContrast": 0,
      "runUserMatugenTemplates": true,
      "matugenTargetMonitor": "",
      "popupTransparency": 1,
      "dockTransparency": 1,
      "widgetBackgroundColor": "sc",
      "widgetColorMode": "colorful",
      "controlCenterTileColorMode": "primary",
      "buttonColorMode": "primary",
      "cornerRadius": 7,
      "niriLayoutGapsOverride": -1,
      "niriLayoutRadiusOverride": -1,
      "niriLayoutBorderSize": -1,
      "mangoLayoutGapsOverride": -1,
      "mangoLayoutRadiusOverride": -1,
      "mangoLayoutBorderSize": -1,
      "firstDayOfWeek": -1,
      "showWeekNumber": false,
      "use24HourClock": true,
      "showSeconds": false,
      "padHours12Hour": false,
      "useFahrenheit": false,
      "windSpeedUnit": "kmh",
      "nightModeEnabled": false,
      "animationSpeed": 1,
      "customAnimationDuration": 500,
      "syncComponentAnimationSpeeds": true,
      "popoutAnimationSpeed": 1,
      "popoutCustomAnimationDuration": 150,
      "modalAnimationSpeed": 1,
      "modalCustomAnimationDuration": 150,
      "enableRippleEffects": true,
      "m3ElevationEnabled": true,
      "m3ElevationIntensity": 12,
      "m3ElevationOpacity": 30,
      "m3ElevationColorMode": "default",
      "m3ElevationLightDirection": "top",
      "m3ElevationCustomColor": "#000000",
      "modalElevationEnabled": true,
      "popoutElevationEnabled": true,
      "barElevationEnabled": false,
      "blurEnabled": false,
      "blurForegroundLayers": false,
      "blurLayerOutlineOpacity": 0,
      "blurBorderColor": "outline",
      "blurBorderCustomColor": "#ffffff",
      "blurBorderOpacity": 0.35,
      "wallpaperFillMode": "Fill",
      "blurredWallpaperLayer": false,
      "blurWallpaperOnOverview": false,
      "showLauncherButton": true,
      "showWorkspaceSwitcher": true,
      "showFocusedWindow": true,
      "showWeather": true,
      "showMusic": true,
      "showClipboard": true,
      "showCpuUsage": true,
      "showMemUsage": true,
      "showCpuTemp": true,
      "showGpuTemp": true,
      "selectedGpuIndex": 0,
      "enabledGpuPciIds": [],
      "showSystemTray": true,
      "systemTrayIconTintMode": "none",
      "systemTrayIconTintSaturation": 50,
      "systemTrayIconTintStrength": 135,
      "showClock": true,
      "showNotificationButton": true,
      "showBattery": true,
      "showControlCenterButton": true,
      "showCapsLockIndicator": true,
      "controlCenterShowNetworkIcon": true,
      "controlCenterShowBluetoothIcon": true,
      "controlCenterShowAudioIcon": true,
      "controlCenterShowAudioPercent": false,
      "controlCenterShowVpnIcon": true,
      "controlCenterShowBrightnessIcon": false,
      "controlCenterShowBrightnessPercent": false,
      "controlCenterShowMicIcon": false,
      "controlCenterShowMicPercent": true,
      "controlCenterShowBatteryIcon": false,
      "controlCenterShowPrinterIcon": false,
      "controlCenterShowScreenSharingIcon": true,
      "showPrivacyButton": true,
      "privacyShowMicIcon": false,
      "privacyShowCameraIcon": false,
      "privacyShowScreenShareIcon": false,
      "controlCenterWidgets": [
        { "id": "inputVolumeSlider", "enabled": true, "width": 50 },
        { "id": "volumeSlider", "enabled": true, "width": 50 },
        { "id": "wifi", "enabled": true, "width": 50 },
        { "id": "audioOutput", "enabled": true, "width": 50 },
        { "id": "audioInput", "enabled": true, "width": 50 },
        { "id": "nightMode", "enabled": true, "width": 50 },
        { "id": "builtin_tailscale", "enabled": true, "width": 50 },
        { "id": "bluetooth", "enabled": true, "width": 50 },
        { "id": "brightnessSlider", "enabled": true, "width": 100 }
      ],
      "showWorkspaceIndex": true,
      "showWorkspaceName": true,
      "showWorkspacePadding": false,
      "workspaceScrolling": false,
      "showWorkspaceApps": false,
      "workspaceDragReorder": true,
      "maxWorkspaceIcons": 3,
      "workspaceAppIconSizeOffset": 0,
      "groupWorkspaceApps": true,
      "workspaceFollowFocus": false,
      "showOccupiedWorkspacesOnly": false,
      "reverseScrolling": false,
      "dwlShowAllTags": false,
      "workspaceActiveAppHighlightEnabled": false,
      "workspaceColorMode": "default",
      "workspaceOccupiedColorMode": "none",
      "workspaceUnfocusedColorMode": "sch",
      "workspaceUrgentColorMode": "default",
      "workspaceFocusedBorderEnabled": false,
      "workspaceFocusedBorderColor": "primary",
      "workspaceFocusedBorderThickness": 2,
      "workspaceNameIcons": {},
      "waveProgressEnabled": true,
      "scrollTitleEnabled": true,
      "mediaAdaptiveWidthEnabled": true,
      "audioVisualizerEnabled": true,
      "audioScrollMode": "volume",
      "audioWheelScrollAmount": 5,
      "clockCompactMode": false,
      "focusedWindowCompactMode": false,
      "runningAppsCompactMode": true,
      "barMaxVisibleApps": 0,
      "barMaxVisibleRunningApps": 0,
      "barShowOverflowBadge": true,
      "appsDockHideIndicators": false,
      "appsDockColorizeActive": true,
      "appsDockActiveColorMode": "primary",
      "appsDockEnlargeOnHover": true,
      "appsDockEnlargePercentage": 125,
      "appsDockIconSizePercentage": 100,
      "keyboardLayoutNameCompactMode": false,
      "runningAppsCurrentWorkspace": true,
      "runningAppsGroupByApp": false,
      "runningAppsCurrentMonitor": false,
      "appIdSubstitutions": [],
      "centeringMode": "index",
      "clockDateFormat": "d MMM, ddd",
      "lockDateFormat": "",
      "greeterRememberLastSession": true,
      "greeterRememberLastUser": true,
      "greeterEnableFprint": false,
      "greeterEnableU2f": false,
      "greeterWallpaperPath": "",
      "greeterUse24HourClock": true,
      "greeterShowSeconds": false,
      "greeterPadHours12Hour": false,
      "greeterLockDateFormat": "",
      "greeterFontFamily": "",
      "greeterWallpaperFillMode": "",
      "mediaSize": 1,
      "appLauncherViewMode": "list",
      "spotlightModalViewMode": "list",
      "browserPickerViewMode": "grid",
      "browserUsageHistory": {},
      "appPickerViewMode": "grid",
      "filePickerUsageHistory": {},
      "sortAppsAlphabetically": false,
      "appLauncherGridColumns": 4,
      "spotlightCloseNiriOverview": true,
      "rememberLastQuery": false,
      "spotlightSectionViewModes": {},
      "appDrawerSectionViewModes": {},
      "niriOverviewOverlayEnabled": true,
      "dankLauncherV2Size": "compact",
      "dankLauncherV2BorderEnabled": false,
      "dankLauncherV2BorderThickness": 2,
      "dankLauncherV2BorderColor": "primary",
      "dankLauncherV2ShowFooter": true,
      "dankLauncherV2UnloadOnClose": false,
      "dankLauncherV2IncludeFilesInAll": false,
      "dankLauncherV2IncludeFoldersInAll": false,
      "useAutoLocation": true,
      "weatherEnabled": true,
      "networkPreference": "auto",
      "iconTheme": "System Default",
      "cursorSettings": {
        "theme": "System Default",
        "size": 24,
        "niri": { "hideWhenTyping": false, "hideAfterInactiveMs": 0 },
        "dwl": { "cursorHideTimeout": 0 }
      },
      "launcherLogoMode": "os",
      "launcherLogoCustomPath": "",
      "launcherLogoColorOverride": "",
      "launcherLogoColorInvertOnMode": false,
      "launcherLogoBrightness": 0.5,
      "launcherLogoContrast": 1,
      "launcherLogoSizeOffset": 0,
      "fontFamily": "Inter Variable",
      "monoFontFamily": "Fira Code",
      "fontWeight": 600,
      "fontScale": 1,
      "notepadUseMonospace": true,
      "notepadFontFamily": "",
      "notepadFontSize": 14,
      "notepadShowLineNumbers": false,
      "notepadTransparencyOverride": -1,
      "notepadLastCustomTransparency": 0.7,
      "soundsEnabled": true,
      "useSystemSoundTheme": false,
      "soundLogin": true,
      "soundNewNotification": true,
      "soundVolumeChanged": true,
      "soundPluggedIn": true,
      "acMonitorTimeout": 0,
      "acLockTimeout": 0,
      "acSuspendTimeout": 0,
      "acSuspendBehavior": 0,
      "acProfileName": "",
      "acPostLockMonitorTimeout": 0,
      "batteryMonitorTimeout": 0,
      "batteryLockTimeout": 0,
      "batterySuspendTimeout": 0,
      "batterySuspendBehavior": 0,
      "batteryProfileName": "",
      "batteryPostLockMonitorTimeout": 0,
      "batteryChargeLimit": 100,
      "lockBeforeSuspend": false,
      "loginctlLockIntegration": true,
      "fadeToLockEnabled": true,
      "fadeToLockGracePeriod": 5,
      "fadeToDpmsEnabled": true,
      "fadeToDpmsGracePeriod": 5,
      "launchPrefix": "",
      "brightnessDevicePins": {},
      "wifiNetworkPins": {},
      "bluetoothDevicePins": {},
      "audioInputDevicePins": {},
      "audioOutputDevicePins": {},
      "gtkThemingEnabled": false,
      "qtThemingEnabled": false,
      "syncModeWithPortal": true,
      "terminalsAlwaysDark": false,
      "muxType": "tmux",
      "muxUseCustomCommand": false,
      "muxCustomCommand": "",
      "muxSessionFilter": "",
      "runDmsMatugenTemplates": false,
      "matugenTemplateGtk": true,
      "matugenTemplateNiri": true,
      "matugenTemplateMangowc": true,
      "matugenTemplateQt5ct": true,
      "matugenTemplateQt6ct": true,
      "matugenTemplateFirefox": true,
      "matugenTemplatePywalfox": true,
      "matugenTemplateZenBrowser": true,
      "matugenTemplateVesktop": true,
      "matugenTemplateEquibop": true,
      "matugenTemplateGhostty": true,
      "matugenTemplateKitty": true,
      "matugenTemplateFoot": true,
      "matugenTemplateAlacritty": true,
      "matugenTemplateNeovim": false,
      "matugenTemplateWezterm": true,
      "matugenTemplateDgop": true,
      "matugenTemplateKcolorscheme": false,
      "matugenTemplateVscode": true,
      "matugenTemplateEmacs": true,
      "matugenTemplateZed": true,
      "matugenTemplateNeovimSettings": {
        "dark": { "baseTheme": "github_dark", "harmony": 0.5 },
        "light": { "baseTheme": "github_light", "harmony": 0.5 }
      },
      "matugenTemplateNeovimSetBackground": true,
      "showDock": false,
      "dockAutoHide": false,
      "dockSmartAutoHide": false,
      "dockGroupByApp": false,
      "dockRestoreSpecialWorkspaceOnClick": false,
      "dockOpenOnOverview": false,
      "dockPosition": 1,
      "dockSpacing": 4,
      "dockBottomGap": 0,
      "dockMargin": 0,
      "dockIconSize": 40,
      "dockIndicatorStyle": "circle",
      "dockBorderEnabled": false,
      "dockBorderColor": "surfaceText",
      "dockBorderOpacity": 1,
      "dockBorderThickness": 1,
      "dockIsolateDisplays": false,
      "dockLauncherEnabled": false,
      "dockLauncherLogoMode": "apps",
      "dockLauncherLogoCustomPath": "",
      "dockLauncherLogoColorOverride": "",
      "dockLauncherLogoSizeOffset": 0,
      "dockLauncherLogoBrightness": 0.5,
      "dockLauncherLogoContrast": 1,
      "dockMaxVisibleApps": 0,
      "dockMaxVisibleRunningApps": 0,
      "dockShowOverflowBadge": true,
      "notificationOverlayEnabled": true,
      "notificationPopupShadowEnabled": true,
      "notificationPopupPrivacyMode": false,
      "modalDarkenBackground": true,
      "lockScreenShowPowerActions": true,
      "lockScreenShowSystemIcons": true,
      "lockScreenShowTime": true,
      "lockScreenShowDate": true,
      "lockScreenShowProfileImage": true,
      "lockScreenShowPasswordField": true,
      "lockScreenShowMediaPlayer": true,
      "lockScreenPowerOffMonitorsOnLock": false,
      "lockAtStartup": false,
      "enableFprint": false,
      "maxFprintTries": 15,
      "enableU2f": false,
      "u2fMode": "or",
      "lockScreenActiveMonitor": "all",
      "lockScreenInactiveColor": "#000000",
      "lockScreenNotificationMode": 3,
      "lockScreenVideoEnabled": false,
      "lockScreenVideoPath": "",
      "lockScreenVideoCycling": false,
      "hideBrightnessSlider": false,
      "notificationTimeoutLow": 5000,
      "notificationTimeoutNormal": 5000,
      "notificationTimeoutCritical": 0,
      "notificationCompactMode": true,
      "notificationPopupPosition": 3,
      "notificationAnimationSpeed": 1,
      "notificationCustomAnimationDuration": 400,
      "notificationHistoryEnabled": true,
      "notificationHistoryMaxCount": 50,
      "notificationHistoryMaxAgeDays": 7,
      "notificationHistorySaveLow": true,
      "notificationHistorySaveNormal": true,
      "notificationHistorySaveCritical": true,
      "notificationRules": [],
      "notificationFocusedMonitor": false,
      "osdAlwaysShowValue": true,
      "osdPosition": 5,
      "osdVolumeEnabled": true,
      "osdMediaVolumeEnabled": true,
      "osdMediaPlaybackEnabled": true,
      "osdBrightnessEnabled": true,
      "osdIdleInhibitorEnabled": true,
      "osdMicMuteEnabled": true,
      "osdCapsLockEnabled": true,
      "osdPowerProfileEnabled": true,
      "osdAudioOutputEnabled": true,
      "powerActionConfirm": true,
      "powerActionHoldDuration": 0.5,
      "powerMenuActions": ["reboot", "logout", "poweroff", "lock", "suspend", "restart"],
      "powerMenuDefaultAction": "logout",
      "powerMenuGridLayout": false,
      "customPowerActionLock": "",
      "customPowerActionLogout": "",
      "customPowerActionSuspend": "",
      "customPowerActionHibernate": "",
      "customPowerActionReboot": "",
      "customPowerActionPowerOff": "",
      "updaterHideWidget": false,
      "updaterUseCustomCommand": false,
      "updaterCustomCommand": "",
      "updaterTerminalAdditionalParams": "",
      "displayNameMode": "system",
      "screenPreferences": {
        "wallpaper": []
      },
      "showOnLastDisplay": {},
      "niriOutputSettings": {},
      "displayProfiles": {},
      "activeDisplayProfile": {},
      "displayProfileAutoSelect": false,
      "displayShowDisconnected": false,
      "displaySnapToEdge": true,
      "barConfigs": [
        {
          "id": "default",
          "name": "Main Bar",
          "enabled": true,
          "position": 0,
          "screenPreferences": ["all"],
          "showOnLastDisplay": true,
          "leftWidgets": ["launcherButton", "workspaceSwitcher", { "id": "music", "enabled": true, "mediaSize": 2 }],
          "centerWidgets": [{ "id": "appsDock", "enabled": true }, { "id": "clock", "enabled": true }, { "id": "weather", "enabled": true }],
          "rightWidgets": ["systemTray", "clipboard", "notificationButton", "battery", "controlCenterButton"],
          "spacing": 0,
          "innerPadding": 12,
          "bottomGap": -4,
          "transparency": 0,
          "widgetTransparency": 1,
          "squareCorners": false,
          "noBackground": false,
          "maximizeWidgetIcons": false,
          "maximizeWidgetText": false,
          "removeWidgetPadding": false,
          "widgetPadding": 8,
          "gothCornersEnabled": true,
          "gothCornerRadiusOverride": false,
          "gothCornerRadiusValue": 12,
          "borderEnabled": false,
          "borderColor": "surfaceText",
          "borderOpacity": 1,
          "borderThickness": 9,
          "widgetOutlineEnabled": false,
          "widgetOutlineColor": "primary",
          "widgetOutlineOpacity": 0.81,
          "widgetOutlineThickness": 7,
          "fontScale": 1.07,
          "iconScale": 1.11,
          "autoHide": false,
          "autoHideDelay": 250,
          "showOnWindowsOpen": false,
          "openOnOverview": false,
          "visible": true,
          "popupGapsAuto": true,
          "popupGapsManual": 16,
          "maximizeDetection": true,
          "scrollEnabled": true,
          "scrollXBehavior": "column",
          "scrollYBehavior": "workspace",
          "shadowIntensity": 0,
          "shadowOpacity": 0,
          "shadowColorMode": "default",
          "shadowCustomColor": "#000000",
          "clickThrough": false
        }
      ],
      "desktopClockEnabled": false,
      "desktopClockStyle": "analog",
      "desktopClockTransparency": 0.8,
      "desktopClockColorMode": "primary",
      "desktopClockCustomColor": {
        "r": 1, "g": 1, "b": 1, "a": 1,
        "hsvHue": -1, "hsvSaturation": 0, "hsvValue": 1,
        "hslHue": -1, "hslSaturation": 0, "hslLightness": 1,
        "valid": true
      },
      "desktopClockShowDate": true,
      "desktopClockShowAnalogNumbers": false,
      "desktopClockShowAnalogSeconds": true,
      "desktopClockX": -1,
      "desktopClockY": -1,
      "desktopClockWidth": 280,
      "desktopClockHeight": 180,
      "desktopClockDisplayPreferences": ["all"],
      "systemMonitorEnabled": false,
      "systemMonitorShowHeader": true,
      "systemMonitorTransparency": 0.8,
      "systemMonitorColorMode": "primary",
      "systemMonitorCustomColor": {
        "r": 1, "g": 1, "b": 1, "a": 1,
        "hsvHue": -1, "hsvSaturation": 0, "hsvValue": 1,
        "hslHue": -1, "hslSaturation": 0, "hslLightness": 1,
        "valid": true
      },
      "systemMonitorShowCpu": true,
      "systemMonitorShowCpuGraph": true,
      "systemMonitorShowCpuTemp": true,
      "systemMonitorShowGpuTemp": false,
      "systemMonitorGpuPciId": "",
      "systemMonitorShowMemory": true,
      "systemMonitorShowMemoryGraph": true,
      "systemMonitorShowNetwork": true,
      "systemMonitorShowNetworkGraph": true,
      "systemMonitorShowDisk": true,
      "systemMonitorShowTopProcesses": false,
      "systemMonitorTopProcessCount": 3,
      "systemMonitorTopProcessSortBy": "cpu",
      "systemMonitorGraphInterval": 60,
      "systemMonitorLayoutMode": "auto",
      "systemMonitorX": -1,
      "systemMonitorY": -1,
      "systemMonitorWidth": 320,
      "systemMonitorHeight": 480,
      "systemMonitorDisplayPreferences": ["all"],
      "systemMonitorVariants": [],
      "desktopWidgetPositions": {},
      "desktopWidgetGridSettings": {},
      "desktopWidgetInstances": [],
      "desktopWidgetGroups": [],
      "builtInPluginSettings": {
        "dms_settings_search": { "trigger": "?" }
      },
      "clipboardEnterToPaste": false,
      "launcherPluginVisibility": {},
      "launcherPluginOrder": [],
      "configVersion": 5
    }
  '';
  dmsSession = builtins.fromJSON ''
    {
      "isLightMode": false,
      "doNotDisturb": false,
      "doNotDisturbUntil": 0,
      "wallpaperPath": "/home/uday/Downloads/cube.gif",
      "perMonitorWallpaper": false,
      "monitorWallpapers": {},
      "perModeWallpaper": false,
      "wallpaperPathLight": "/home/uday/Downloads/test.jpg",
      "wallpaperPathDark": "/home/uday/Downloads/test.jpg",
      "monitorWallpapersLight": {},
      "monitorWallpapersDark": {},
      "monitorWallpaperFillModes": {},
      "wallpaperTransition": "pixelate",
      "includedTransitions": ["fade", "wipe", "disc", "stripes", "iris bloom", "pixelate", "portal"],
      "wallpaperCyclingEnabled": false,
      "wallpaperCyclingMode": "interval",
      "wallpaperCyclingInterval": 300,
      "wallpaperCyclingTime": "06:00",
      "monitorCyclingSettings": {},
      "nightModeEnabled": false,
      "nightModeTemperature": 4500,
      "nightModeHighTemperature": 6500,
      "nightModeAutoEnabled": false,
      "nightModeAutoMode": "time",
      "nightModeStartHour": 18,
      "nightModeStartMinute": 0,
      "nightModeEndHour": 6,
      "nightModeEndMinute": 0,
      "latitude": 0,
      "longitude": 0,
      "nightModeUseIPLocation": false,
      "nightModeLocationProvider": "",
      "themeModeAutoEnabled": false,
      "themeModeAutoMode": "time",
      "themeModeStartHour": 18,
      "themeModeStartMinute": 0,
      "themeModeEndHour": 6,
      "themeModeEndMinute": 0,
      "themeModeShareGammaSettings": true,
      "weatherLocation": "Gurugram, Haryana",
      "weatherCoordinates": "28.4646148,77.0299194",
      "pinnedApps": [],
      "barPinnedApps": [],
      "dockLauncherPosition": 0,
      "hiddenTrayIds": [],
      "trayItemOrder": [],
      "recentColors": [],
      "showThirdPartyPlugins": true,
      "launchPrefix": "",
      "lastBrightnessDevice": "",
      "brightnessExponentialDevices": {},
      "brightnessUserSetValues": {},
      "brightnessExponentValues": {},
      "selectedGpuIndex": 0,
      "nvidiaGpuTempEnabled": false,
      "nonNvidiaGpuTempEnabled": false,
      "enabledGpuPciIds": [],
      "wifiDeviceOverride": "",
      "weatherHourlyDetailed": true,
      "hiddenApps": [],
      "appOverrides": {},
      "searchAppActions": true,
      "vpnLastConnected": "",
      "lastPlayerIdentity": "Mozilla firefox",
      "deviceMaxVolumes": {},
      "hiddenOutputDeviceNames": [],
      "hiddenInputDeviceNames": [],
      "locale": "",
      "timeLocale": "",
      "launcherLastMode": "all",
      "launcherLastQuery": "",
      "launcherQueryHistory": [],
      "appDrawerLastMode": "apps",
      "niriOverviewLastMode": "apps",
      "settingsSidebarExpandedIds": ",power_security,dock_launcher,displays,personalization,system,workspaces_widgets,dankbar,",
      "settingsSidebarCollapsedIds": ",",
      "configVersion": 3
    }
  '';
  persistedDmsSettings = builtins.fromJSON ''
    {
      "currentThemeName": "custom",
      "currentThemeCategory": "registry",
      "customThemeFile": "/home/uday/.config/DankMaterialShell/themes/stylix/theme.json",
      "registryThemeVariants": {},
      "matugenScheme": "scheme-tonal-spot",
      "matugenContrast": 0,
      "runUserMatugenTemplates": true,
      "matugenTargetMonitor": "",
      "popupTransparency": 1,
      "dockTransparency": 1,
      "floatingWindowSyncGlobal": false,
      "floatingWindowTransparency": 1,
      "floatingWindowForegroundLayers": true,
      "floatingWindowForegroundTransparency": 1,
      "dmsWindowsFloating": true,
      "widgetBackgroundColor": "sc",
      "widgetBackgroundCustomColor": "#6750A4",
      "widgetBackgroundCustomStrength": 0.5,
      "widgetColorMode": "colorful",
      "controlCenterTileColorMode": "primary",
      "buttonColorMode": "primary",
      "cornerRadius": 7,
      "niriLayoutGapsOverride": -1,
      "niriLayoutRadiusOverride": -1,
      "niriLayoutBorderSize": -1,
      "hyprlandLayoutGapsOverride": -1,
      "hyprlandLayoutGapsOutOverride": -1,
      "hyprlandLayoutRadiusOverride": -1,
      "hyprlandLayoutBorderSize": -1,
      "hyprlandResizeOnBorder": false,
      "mangoLayoutGapsOverride": -1,
      "mangoLayoutGapsOutOverride": -1,
      "mangoLayoutRadiusOverride": -1,
      "mangoLayoutBorderSize": -1,
      "mangoTrackpadNaturalScrolling": true,
      "mouseAccelProfile": "default",
      "mouseAccelSpeed": 0,
      "mouseLeftHanded": false,
      "mouseMiddleEmulation": false,
      "mouseNaturalScroll": false,
      "mouseScrollFactor": 1,
      "mouseScrollMethod": "default",
      "touchpadAccelProfile": "default",
      "touchpadAccelSpeed": 0,
      "touchpadDisableOnExternalMouse": false,
      "touchpadDisableWhileTyping": true,
      "touchpadDragLock": false,
      "touchpadMiddleEmulation": false,
      "touchpadNaturalScroll": true,
      "touchpadScrollFactor": 1,
      "touchpadScrollMethod": "default",
      "touchpadTapAndDrag": true,
      "touchpadTapToClick": true,
      "keyboardLayouts": "",
      "keyboardVariants": "",
      "keyboardModel": "",
      "keyboardOptions": "",
      "keyboardKeymapFile": "",
      "keyboardTrackLayout": "",
      "keyboardRepeatDelay": 0,
      "keyboardRepeatRate": 0,
      "keyboardNumlock": false,
      "firstDayOfWeek": -1,
      "showWeekNumber": false,
      "calendarBackend": "auto",
      "clockFormat": "24h",
      "showSeconds": false,
      "padHours12Hour": false,
      "useFahrenheit": false,
      "windSpeedUnit": "kmh",
      "nightModeEnabled": false,
      "animationSpeed": 1,
      "customAnimationDuration": 500,
      "syncComponentAnimationSpeeds": true,
      "popoutAnimationSpeed": 1,
      "popoutCustomAnimationDuration": 150,
      "modalAnimationSpeed": 1,
      "modalCustomAnimationDuration": 150,
      "enableRippleEffects": true,
      "animationVariant": 0,
      "motionEffect": 0,
      "m3ElevationEnabled": true,
      "m3ElevationIntensity": 12,
      "m3ElevationOpacity": 30,
      "m3ElevationColorMode": "default",
      "m3ElevationLightDirection": "top",
      "m3ElevationCustomColor": "#000000",
      "modalElevationEnabled": true,
      "popoutElevationEnabled": true,
      "barElevationEnabled": false,
      "blurEnabled": false,
      "blurForegroundLayers": true,
      "foregroundLayerTransparency": 1,
      "blurLayerOutlineOpacity": 0.4,
      "blurBorderEnabled": true,
      "blurBorderColor": "outline",
      "blurBorderCustomColor": "#ffffff",
      "blurBorderOpacity": 0.35,
      "wallpaperFillMode": "Fill",
      "blurredWallpaperLayer": false,
      "blurWallpaperOnOverview": false,
      "wallpaperBackgroundColorMode": "black",
      "wallpaperBackgroundCustomColor": "#000000",
      "showLauncherButton": true,
      "showWorkspaceSwitcher": true,
      "showFocusedWindow": true,
      "showWeather": true,
      "showMusic": true,
      "showClipboard": true,
      "showCpuUsage": true,
      "showMemUsage": true,
      "showCpuTemp": true,
      "showGpuTemp": true,
      "selectedGpuIndex": 0,
      "enabledGpuPciIds": [],
      "showSystemTray": true,
      "systemTrayIconTintMode": "none",
      "systemTrayIconTintSaturation": 50,
      "systemTrayIconTintStrength": 135,
      "showClock": true,
      "showNotificationButton": true,
      "showBattery": true,
      "showBatteryPercent": true,
      "showBatteryPercentOnlyOnBattery": false,
      "showBatteryTime": false,
      "showBatteryTimeOnlyOnBattery": false,
      "batteryPillStyle": false,
      "batteryPillPercentSign": false,
      "showControlCenterButton": true,
      "showCapsLockIndicator": true,
      "controlCenterShowNetworkIcon": true,
      "controlCenterShowBluetoothIcon": true,
      "controlCenterShowAudioIcon": true,
      "controlCenterShowAudioPercent": false,
      "controlCenterShowVpnIcon": true,
      "controlCenterShowBrightnessIcon": false,
      "controlCenterShowBrightnessPercent": false,
      "controlCenterShowMicIcon": false,
      "controlCenterShowMicPercent": true,
      "controlCenterShowBatteryIcon": false,
      "controlCenterShowPrinterIcon": false,
      "controlCenterShowScreenSharingIcon": true,
      "controlCenterShowIdleInhibitorIcon": false,
      "controlCenterShowDoNotDisturbIcon": false,
      "showPrivacyButton": true,
      "privacyShowMicIcon": false,
      "privacyShowCameraIcon": false,
      "privacyShowScreenShareIcon": false,
      "controlCenterWidgets": [
        { "enabled": true, "id": "inputVolumeSlider", "width": 50 },
        { "enabled": true, "id": "volumeSlider", "width": 50 },
        { "enabled": true, "id": "wifi", "width": 50 },
        { "enabled": true, "id": "audioOutput", "width": 50 },
        { "enabled": true, "id": "audioInput", "width": 50 },
        { "enabled": true, "id": "nightMode", "width": 50 },
        { "enabled": true, "id": "builtin_tailscale", "width": 50 },
        { "enabled": true, "id": "bluetooth", "width": 50 },
        { "enabled": true, "id": "brightnessSlider", "width": 100 }
      ],
      "showWorkspaceIndex": true,
      "showWorkspaceName": true,
      "showWorkspacePadding": false,
      "workspaceScrolling": false,
      "showWorkspaceApps": false,
      "workspaceDragReorder": true,
      "maxWorkspaceIcons": 3,
      "workspaceAppIconSizeOffset": 0,
      "groupWorkspaceApps": true,
      "groupActiveWorkspaceApps": false,
      "workspaceFollowFocus": false,
      "showOccupiedWorkspacesOnly": false,
      "reverseScrolling": false,
      "dwlShowAllTags": false,
      "workspaceActiveAppHighlightEnabled": false,
      "workspaceColorMode": "default",
      "workspaceFocusedCustomColor": "#6750A4",
      "workspaceOccupiedColorMode": "none",
      "workspaceOccupiedCustomColor": "#625B71",
      "workspaceUnfocusedColorMode": "sch",
      "workspaceUnfocusedCustomColor": "#49454E",
      "workspaceUrgentColorMode": "default",
      "workspaceUrgentCustomColor": "#B3261E",
      "workspaceFocusedBorderEnabled": false,
      "workspaceFocusedBorderColor": "primary",
      "workspaceFocusedBorderCustomColor": "#6750A4",
      "workspaceFocusedBorderThickness": 2,
      "workspaceUnfocusedMonitorSeparateAppearance": false,
      "workspaceUnfocusedMonitorColorMode": "default",
      "workspaceUnfocusedMonitorFocusedCustomColor": "#6750A4",
      "workspaceUnfocusedMonitorOccupiedColorMode": "none",
      "workspaceUnfocusedMonitorOccupiedCustomColor": "#625B71",
      "workspaceUnfocusedMonitorUnfocusedColorMode": "default",
      "workspaceUnfocusedMonitorUnfocusedCustomColor": "#49454E",
      "workspaceUnfocusedMonitorUrgentColorMode": "default",
      "workspaceUnfocusedMonitorUrgentCustomColor": "#B3261E",
      "workspaceUnfocusedMonitorBorderEnabled": false,
      "workspaceUnfocusedMonitorBorderColor": "primary",
      "workspaceUnfocusedMonitorBorderCustomColor": "#6750A4",
      "workspaceUnfocusedMonitorBorderThickness": 2,
      "workspaceNameIcons": {},
      "waveProgressEnabled": true,
      "scrollTitleEnabled": true,
      "mediaAdaptiveWidthEnabled": true,
      "audioVisualizerEnabled": true,
      "mediaUseAlbumArtAccent": false,
      "appleMusicAnimatedArtEnabled": false,
      "audioScrollMode": "volume",
      "audioWheelScrollAmount": 5,
      "audioDeviceScrollVolumeEnabled": false,
      "mediaExcludePlayers": [],
      "clockCompactMode": false,
      "focusedWindowCompactMode": false,
      "focusedWindowSize": 1,
      "focusedWindowShowIcon": true,
      "runningAppsCompactMode": true,
      "barMaxVisibleApps": 0,
      "barMaxVisibleRunningApps": 0,
      "barShowOverflowBadge": true,
      "trayAutoOverflow": true,
      "trayPopupSingleLine": true,
      "trayMaxVisibleItems": 0,
      "appsDockHideIndicators": false,
      "appsDockColorizeActive": true,
      "appsDockActiveColorMode": "primary",
      "appsDockEnlargeOnHover": true,
      "appsDockEnlargePercentage": 125,
      "appsDockIconSizePercentage": 100,
      "keyboardLayoutNameCompactMode": false,
      "keyboardLayoutNameShowIcon": false,
      "runningAppsCurrentWorkspace": true,
      "runningAppsGroupByApp": false,
      "runningAppsCurrentMonitor": false,
      "appIdSubstitutions": [],
      "centeringMode": "index",
      "clockDateFormat": "d MMM, ddd",
      "lockDateFormat": "",
      "greeterRememberLastSession": true,
      "greeterRememberLastUser": true,
      "greeterAutoLogin": false,
      "greeterEnableFprint": false,
      "greeterEnableU2f": false,
      "greeterWallpaperPath": "",
      "greeterLockDateFormat": "",
      "greeterFontFamily": "",
      "greeterWallpaperFillMode": "",
      "greeterPamExternallyManaged": false,
      "greeterSyncPending": false,
      "greeterSyncBaseline": {},
      "mediaSize": 1,
      "appLauncherViewMode": "list",
      "spotlightModalViewMode": "list",
      "browserPickerViewMode": "grid",
      "browserUsageHistory": {},
      "appPickerViewMode": "grid",
      "filePickerUsageHistory": {},
      "sortAppsAlphabetically": false,
      "appLauncherGridColumns": 4,
      "spotlightCloseNiriOverview": true,
      "rememberLastQuery": false,
      "rememberLastMode": true,
      "spotlightSectionViewModes": {},
      "appDrawerSectionViewModes": {},
      "niriOverviewOverlayEnabled": true,
      "niriOverviewLauncherStyle": "full",
      "dankLauncherV2Size": "compact",
      "dankLauncherV2ShowSourceBadges": true,
      "dankLauncherV2BorderEnabled": false,
      "dankLauncherV2BorderThickness": 2,
      "dankLauncherV2BorderColor": "primary",
      "dankLauncherV2ShowFooter": true,
      "dankLauncherV2UnloadOnClose": false,
      "dankLauncherV2IncludeFilesInAll": false,
      "dankLauncherV2IncludeFoldersInAll": false,
      "launcherUseOverlayLayer": false,
      "launcherStyle": "full",
      "spotlightBarShowModeChips": false,
      "keybindsFloatingWindow": false,
      "useAutoLocation": true,
      "weatherEnabled": true,
      "dashTabs": [
        { "id": "overview", "enabled": true },
        { "id": "media", "enabled": true },
        { "id": "wallpaper", "enabled": true },
        { "id": "weather", "enabled": true },
        { "id": "settings", "enabled": true }
      ],
      "networkPreference": "auto",
      "iconThemeDark": "System Default",
      "iconThemeLight": "System Default",
      "iconThemePerMode": false,
      "lastAppliedIconTheme": "",
      "cursorSettings": {
        "dwl": { "cursorHideTimeout": 0 },
        "niri": { "hideAfterInactiveMs": 0, "hideWhenTyping": false },
        "size": 24,
        "theme": "System Default"
      },
      "launcherLogoMode": "os",
      "launcherLogoCustomPath": "",
      "launcherLogoColorOverride": "",
      "launcherLogoColorInvertOnMode": false,
      "launcherLogoBrightness": 0.5,
      "launcherLogoContrast": 1,
      "launcherLogoSizeOffset": 0,
      "fontFamily": "Inter Variable",
      "monoFontFamily": "Fira Code",
      "fontWeight": 600,
      "fontScale": 1,
      "textRenderType": 0,
      "textRenderQuality": 0,
      "notepadUseMonospace": true,
      "notepadFontFamily": "",
      "notepadFontSize": 14,
      "notificationSummaryFontSize": 0,
      "notificationBodyFontSize": 0,
      "notepadShowLineNumbers": false,
      "notepadAutoSave": false,
      "notepadSlideoutSide": "right",
      "notepadDefaultMode": "slideout",
      "notepadTransparencyOverride": -1,
      "notepadLastCustomTransparency": 0.7,
      "notepadUseCompositorGap": false,
      "notepadEdgeGap": 0,
      "soundsEnabled": true,
      "useSystemSoundTheme": false,
      "soundLogin": true,
      "soundNewNotification": true,
      "soundVolumeChanged": true,
      "soundPluggedIn": true,
      "muteSoundsWhenMediaPlaying": true,
      "acMonitorTimeout": 0,
      "acLockTimeout": 0,
      "acSuspendTimeout": 0,
      "acSuspendBehavior": 0,
      "acProfileName": "",
      "acPostLockMonitorTimeout": 0,
      "batteryMonitorTimeout": 0,
      "batteryLockTimeout": 0,
      "batterySuspendTimeout": 0,
      "batterySuspendBehavior": 0,
      "batteryProfileName": "",
      "batteryPostLockMonitorTimeout": 0,
      "batteryChargeLimit": 100,
      "batteryNotifyChargeLimit": false,
      "batteryCriticalThreshold": 10,
      "batteryNotifyCritical": true,
      "batteryLowThreshold": 20,
      "batteryNotifyLow": false,
      "batteryChargeLimitNotificationType": 0,
      "batteryLowNotificationType": 0,
      "batteryCriticalNotificationType": 1,
      "batteryAutoPowerSaver": false,
      "lowerDisplayRefreshRateOnBattery": false,
      "lockBeforeSuspend": false,
      "loginctlLockIntegration": true,
      "fadeToLockEnabled": true,
      "fadeToLockGracePeriod": 5,
      "fadeToDpmsEnabled": true,
      "fadeToDpmsGracePeriod": 5,
      "launchPrefix": "",
      "syncModeWithPortal": true,
      "terminalsAlwaysDark": false,
      "muxType": "tmux",
      "muxUseCustomCommand": false,
      "muxCustomCommand": "",
      "muxSessionFilter": "",
      "runDmsMatugenTemplates": false,
      "matugenTemplateGtk": true,
      "matugenTemplateNiri": true,
      "matugenTemplateHyprland": true,
      "matugenTemplateMangowc": true,
      "matugenTemplateQt5ct": true,
      "matugenTemplateQt6ct": true,
      "matugenTemplateFirefox": true,
      "matugenTemplatePywalfox": true,
      "matugenTemplateZenBrowser": true,
      "matugenTemplateVesktop": true,
      "matugenTemplateVencord": true,
      "matugenTemplateEquibop": true,
      "matugenTemplateGhostty": true,
      "matugenTemplateKitty": true,
      "matugenTemplateFoot": true,
      "matugenTemplateAlacritty": true,
      "matugenTemplateNeovim": false,
      "matugenTemplateWezterm": true,
      "matugenTemplateDgop": true,
      "matugenTemplateKcolorscheme": false,
      "matugenTemplateVscode": true,
      "matugenTemplateEmacs": true,
      "matugenTemplateZed": true,
      "matugenTemplateNeovimSettings": {
        "dark": { "baseTheme": "github_dark", "harmony": 0.5 },
        "light": { "baseTheme": "github_light", "harmony": 0.5 }
      },
      "matugenTemplateNeovimSetBackground": true,
      "showDock": false,
      "dockAutoHide": false,
      "dockSmartAutoHide": false,
      "dockUseOverlayLayer": false,
      "dockGroupByApp": false,
      "dockRestoreSpecialWorkspaceOnClick": false,
      "dockOpenOnOverview": false,
      "dockPosition": 1,
      "dockSpacing": 4,
      "dockBottomGap": 0,
      "dockMargin": 0,
      "dockIconSize": 40,
      "dockIndicatorStyle": "circle",
      "dockBorderEnabled": false,
      "dockBorderColor": "surfaceText",
      "dockBorderOpacity": 1,
      "dockBorderThickness": 1,
      "dockIsolateDisplays": false,
      "dockLauncherEnabled": false,
      "dockLauncherLogoMode": "apps",
      "dockLauncherLogoCustomPath": "",
      "dockLauncherLogoColorOverride": "",
      "dockLauncherLogoSizeOffset": 0,
      "dockLauncherLogoBrightness": 0.5,
      "dockLauncherLogoContrast": 1,
      "dockMaxVisibleApps": 0,
      "dockMaxVisibleRunningApps": 0,
      "dockShowOverflowBadge": true,
      "dockShowTrash": false,
      "dockTrashFileManager": "default",
      "dockTrashCustomCommand": "",
      "notificationOverlayEnabled": true,
      "notificationPopupShadowEnabled": true,
      "notificationPopupPrivacyMode": false,
      "notificationForegroundLayers": true,
      "modalDarkenBackground": true,
      "lockScreenShowPowerActions": true,
      "lockScreenShowSystemIcons": true,
      "lockScreenShowTime": true,
      "lockScreenShowDate": true,
      "lockScreenShowProfileImage": true,
      "lockScreenShowPasswordField": true,
      "lockScreenShowMediaPlayer": true,
      "lockScreenPowerOffMonitorsOnLock": false,
      "lockAtStartup": false,
      "enableFprint": false,
      "maxFprintTries": 15,
      "enableU2f": false,
      "u2fMode": "or",
      "lockPamPath": "",
      "lockScreenSecurityKeyShortcut": "Ctrl+Q",
      "lockScreenSecurityKeyShortcutEnabled": false,
      "lockPamInlineFprint": false,
      "lockPamInlineU2f": false,
      "lockPamExternallyManaged": false,
      "lockU2fPamPath": "",
      "lockScreenInactiveColor": "#000000",
      "lockScreenNotificationMode": 3,
      "lockScreenVideoEnabled": false,
      "lockScreenVideoPath": "",
      "lockScreenVideoCycling": false,
      "lockScreenWallpaperPath": "",
      "lockScreenWallpaperFillMode": "",
      "lockScreenFontFamily": "",
      "hideBrightnessSlider": false,
      "notificationTimeoutLow": 5000,
      "notificationTimeoutNormal": 5000,
      "notificationTimeoutCritical": 0,
      "notificationIgnoreAppTimeout": false,
      "notificationCompactMode": true,
      "notificationShowTimeoutBar": false,
      "notificationDedupeEnabled": true,
      "notificationPopupPosition": 3,
      "notificationAnimationSpeed": 1,
      "notificationCustomAnimationDuration": 400,
      "notificationHistoryEnabled": true,
      "notificationHistoryMaxCount": 50,
      "notificationHistoryMaxAgeDays": 7,
      "notificationHistorySaveLow": true,
      "notificationHistorySaveNormal": true,
      "notificationHistorySaveCritical": true,
      "notificationRules": [],
      "notificationFocusedMonitor": false,
      "osdAlwaysShowValue": true,
      "osdPosition": 5,
      "osdVolumeEnabled": true,
      "osdMediaVolumeEnabled": true,
      "osdMediaPlaybackEnabled": true,
      "osdBrightnessEnabled": true,
      "osdIdleInhibitorEnabled": true,
      "osdMicMuteEnabled": true,
      "osdCapsLockEnabled": true,
      "osdPowerProfileEnabled": true,
      "osdAudioOutputEnabled": true,
      "powerActionConfirm": true,
      "powerActionHoldDuration": 0.5,
      "powerMenuActions": ["reboot", "logout", "poweroff", "lock", "suspend", "restart"],
      "powerMenuDefaultAction": "logout",
      "powerMenuGridLayout": false,
      "customPowerActionLock": "",
      "customPowerActionLogout": "",
      "customPowerActionSuspend": "",
      "customPowerActionHibernate": "",
      "customPowerActionReboot": "",
      "customPowerActionPowerOff": "",
      "customPowerButtons": [],
      "updaterHideWidget": false,
      "updaterCheckOnStart": false,
      "updaterUseCustomCommand": false,
      "updaterCustomCommand": "",
      "updaterTerminalAdditionalParams": "",
      "updaterIntervalSeconds": 1800,
      "updaterIncludeFlatpak": true,
      "updaterAllowAUR": true,
      "updaterIgnoredPackages": [],
      "displayNameMode": "system",
      "screenPreferences": { "wallpaper": [] },
      "showOnLastDisplay": {},
      "niriOutputSettings": {},
      "hyprlandOutputSettings": {},
      "displayProfiles": {},
      "activeDisplayProfile": {},
      "activeDisplayProfileModes": {},
      "displayPreviousRefreshModes": {},
      "displayProfileAutoSelect": false,
      "displayShowDisconnected": false,
      "displaySnapToEdge": true,
      "connectedFrameBarStyleBackups": {},
      "barConfigs": [
        {
          "autoHide": false,
          "autoHideDelay": 250,
          "borderColor": "surfaceText",
          "borderEnabled": false,
          "borderOpacity": 1,
          "borderThickness": 9,
          "bottomGap": -4,
          "centerWidgets": [
            { "enabled": true, "id": "appsDock" },
            { "enabled": true, "id": "clock" },
            { "enabled": true, "id": "weather" }
          ],
          "clickThrough": false,
          "enabled": true,
          "fontScale": 1.07,
          "gothCornerRadiusOverride": false,
          "gothCornerRadiusValue": 12,
          "gothCornersEnabled": false,
          "iconScale": 1.11,
          "id": "default",
          "innerPadding": 12,
          "leftWidgets": [
            "launcherButton",
            "workspaceSwitcher",
            { "enabled": true, "id": "music", "mediaSize": 2 }
          ],
          "maximizeDetection": true,
          "maximizeWidgetIcons": false,
          "maximizeWidgetText": false,
          "name": "Main Bar",
          "noBackground": false,
          "openOnOverview": false,
          "popupGapsAuto": true,
          "popupGapsManual": 16,
          "position": 0,
          "removeWidgetPadding": false,
          "rightWidgets": [
            "systemTray",
            "clipboard",
            "notificationButton",
            "battery",
            "controlCenterButton"
          ],
          "screenPreferences": ["all"],
          "scrollEnabled": true,
          "scrollXBehavior": "column",
          "scrollYBehavior": "workspace",
          "shadowColorMode": "default",
          "shadowCustomColor": "#000000",
          "shadowIntensity": 0,
          "shadowOpacity": 0,
          "showOnLastDisplay": true,
          "showOnWindowsOpen": false,
          "spacing": 0,
          "squareCorners": true,
          "transparency": 0,
          "visible": true,
          "widgetOutlineColor": "primary",
          "widgetOutlineEnabled": false,
          "widgetOutlineOpacity": 0.81,
          "widgetOutlineThickness": 7,
          "widgetPadding": 8,
          "widgetTransparency": 1,
          "barInsetPadding": 10
        }
      ],
      "desktopClockEnabled": false,
      "desktopClockStyle": "analog",
      "desktopClockTransparency": 0.8,
      "desktopClockColorMode": "primary",
      "desktopClockCustomColor": {
        "r": 1,
        "g": 1,
        "b": 1,
        "a": 1,
        "hsvHue": -1,
        "hsvSaturation": 0,
        "hsvValue": 1,
        "hslHue": -1,
        "hslSaturation": 0,
        "hslLightness": 1,
        "valid": true
      },
      "desktopClockShowDate": true,
      "desktopClockShowAnalogNumbers": false,
      "desktopClockShowAnalogSeconds": true,
      "desktopClockX": -1,
      "desktopClockY": -1,
      "desktopClockWidth": 280,
      "desktopClockHeight": 180,
      "desktopClockDisplayPreferences": ["all"],
      "systemMonitorEnabled": false,
      "systemMonitorShowHeader": true,
      "systemMonitorTransparency": 0.8,
      "systemMonitorColorMode": "primary",
      "systemMonitorCustomColor": {
        "r": 1,
        "g": 1,
        "b": 1,
        "a": 1,
        "hsvHue": -1,
        "hsvSaturation": 0,
        "hsvValue": 1,
        "hslHue": -1,
        "hslSaturation": 0,
        "hslLightness": 1,
        "valid": true
      },
      "systemMonitorShowCpu": true,
      "systemMonitorShowCpuGraph": true,
      "systemMonitorShowCpuTemp": true,
      "systemMonitorShowGpuTemp": false,
      "systemMonitorGpuPciId": "",
      "systemMonitorShowMemory": true,
      "systemMonitorShowMemoryGraph": true,
      "systemMonitorShowNetwork": true,
      "systemMonitorShowNetworkGraph": true,
      "systemMonitorShowDisk": true,
      "systemMonitorShowTopProcesses": false,
      "systemMonitorTopProcessCount": 3,
      "systemMonitorTopProcessSortBy": "cpu",
      "systemMonitorGraphInterval": 60,
      "systemMonitorLayoutMode": "auto",
      "systemMonitorX": -1,
      "systemMonitorY": -1,
      "systemMonitorWidth": 320,
      "systemMonitorHeight": 480,
      "systemMonitorDisplayPreferences": ["all"],
      "systemMonitorVariants": [],
      "desktopWidgetPositions": {},
      "desktopWidgetGridSettings": {},
      "desktopWidgetInstances": [],
      "desktopWidgetGroups": [],
      "builtInPluginSettings": {
        "dms_settings_search": { "trigger": "?" }
      },
      "clipboardClickToPaste": false,
      "clipboardEnterToPaste": false,
      "clipboardRememberTypeFilter": false,
      "clipboardTypeFilter": "all",
      "clipboardVisibleEntryActions": ["pin", "edit", "delete"],
      "launcherPluginVisibility": {},
      "launcherPluginOrder": [],
      "frameEnabled": false,
      "frameThickness": 16,
      "frameRounding": 23,
      "frameColor": "",
      "frameOpacity": 1,
      "frameScreenPreferences": ["all"],
      "frameBarSize": 40,
      "frameShowOnOverview": false,
      "frameBlurEnabled": true,
      "frameCloseGaps": true,
      "frameLauncherEmergeSide": "bottom",
      "frameLauncherArcExtender": false,
      "frameLauncherEdgeHover": false,
      "frameMode": "connected",
      "barInsetPaddingShared": -1,
      "barInsetPaddingSyncAll": false,
      "frameBarInsetPadding": -1,
      "configVersion": 13
    }
  '';
  persistedDmsSession = builtins.fromJSON ''
    {
      "isLightMode": false,
      "doNotDisturb": false,
      "doNotDisturbUntil": 0,
      "terminalOverride": "",
      "wallpaperPath": "/nix/store/c0ij7vxxp5407zi8pq70wvsdnr567dxv-source/regular/008.jpg",
      "perMonitorWallpaper": false,
      "monitorWallpapers": {},
      "perModeWallpaper": false,
      "wallpaperPathLight": "/nix/store/c0ij7vxxp5407zi8pq70wvsdnr567dxv-source/regular/047.jpg",
      "wallpaperPathDark": "/nix/store/c0ij7vxxp5407zi8pq70wvsdnr567dxv-source/regular/047.jpg",
      "monitorWallpapersLight": {},
      "monitorWallpapersDark": {},
      "monitorWallpaperFillModes": {},
      "wallpaperTransition": "pixelate",
      "includedTransitions": ["fade", "wipe", "disc", "stripes", "iris bloom", "pixelate", "portal"],
      "wallpaperCyclingEnabled": false,
      "wallpaperCyclingRandom": false,
      "wallpaperCyclingMode": "interval",
      "wallpaperCyclingInterval": 300,
      "wallpaperCyclingTime": "06:00",
      "monitorCyclingSettings": {},
      "nightModeEnabled": false,
      "nightModeTemperature": 4500,
      "nightModeHighTemperature": 6500,
      "nightModeAutoEnabled": false,
      "nightModeAutoMode": "time",
      "nightModeStartHour": 18,
      "nightModeStartMinute": 0,
      "nightModeEndHour": 6,
      "nightModeEndMinute": 0,
      "latitude": 0,
      "longitude": 0,
      "nightModeUseIPLocation": false,
      "nightModeLocationProvider": "",
      "themeModeAutoEnabled": false,
      "themeModeAutoMode": "time",
      "themeModeStartHour": 18,
      "themeModeStartMinute": 0,
      "themeModeEndHour": 6,
      "themeModeEndMinute": 0,
      "themeModeShareGammaSettings": true,
      "weatherLocation": "",
      "weatherCoordinates": "28.4646148,77.0299194",
      "pinnedApps": [],
      "barPinnedApps": [],
      "dockLauncherPosition": 0,
      "hiddenTrayIds": [],
      "trayItemOrder": [],
      "recentColors": [],
      "showThirdPartyPlugins": true,
      "pluginBrowserInstalledFirst": false,
      "pluginBrowserSortMode": "default",
      "launchPrefix": "",
      "lastBrightnessDevice": "",
      "brightnessExponentialDevices": {},
      "brightnessUserSetValues": {},
      "brightnessExponentValues": {},
      "selectedGpuIndex": 0,
      "nvidiaGpuTempEnabled": false,
      "nonNvidiaGpuTempEnabled": false,
      "enabledGpuPciIds": [],
      "wifiDeviceOverride": "",
      "weatherHourlyDetailed": true,
      "hiddenApps": [],
      "appOverrides": {},
      "searchAppActions": true,
      "vpnLastConnected": "",
      "lastPlayerIdentity": "Mozilla firefox",
      "deviceMaxVolumes": {},
      "hiddenOutputDeviceNames": [],
      "hiddenInputDeviceNames": [],
      "locale": "",
      "timeLocale": "",
      "notepadLastMode": "",
      "launcherLastMode": "all",
      "launcherLastFileSearchType": "all",
      "launcherLastQuery": "",
      "launcherQueryHistory": [],
      "appDrawerLastMode": "apps",
      "niriOverviewLastMode": "apps",
      "settingsSidebarExpandedIds": ",power_security,dock_launcher,displays,personalization,system,workspaces_widgets,dankbar,",
      "settingsSidebarCollapsedIds": ",",
      "showConfigReloadToast": true,
      "configVersion": 3
    }
  '';
  defaultWallpaper = "${inputs.wallpapers}/regular/047.jpg";
  base16Theme = {
    primary = c.base0D;
    primaryText = c.base00;
    primaryContainer = c.base0C;
    secondary = c.base0E;
    surface = c.base01;
    surfaceText = c.base05;
    surfaceVariant = c.base02;
    surfaceVariantText = c.base04;
    surfaceTint = c.base0D;
    background = c.base00;
    backgroundText = c.base05;
    outline = c.base03;
    surfaceContainer = c.base01;
    surfaceContainerHigh = c.base03;
    surfaceContainerHighest = c.base04;
    error = c.base08;
    warning = c.base0A;
    info = c.base0C;
  };
in {
  systemd.user.services.dms.Unit.ConditionEnvironment = "XDG_CURRENT_DESKTOP=niri";
  systemd.user.services.dms.Service.Environment = [
    "XDG_DATA_DIRS=${config.home.profileDirectory}/share:/run/current-system/sw/share:/usr/local/share:/usr/share"
    "QT_QPA_PLATFORMTHEME=qt6ct"
    "QS_ICON_THEME=Papirus-Dark"
  ];

  programs.dank-material-shell = {
    enable = true;
    systemd.enable = true;

    enableSystemMonitoring = true;
    # Keep DMS theme stable and sourced from Stylix/Base16 instead of wallpaper-driven recoloring.
    enableDynamicTheming = false;
    enableAudioWavelength = true;
    enableClipboardPaste = true;

    settings =
      dmsSettings
      // persistedDmsSettings
      // {
        currentThemeName = "custom";
        currentThemeCategory = "registry";
        customThemeFile = "${config.home.homeDirectory}/.config/DankMaterialShell/themes/stylix/theme.json";
      };

    session =
      dmsSession
      // persistedDmsSession;
  };

  # DMS selectable installed theme format:
  # ~/.config/DankMaterialShell/themes/<id>/theme.json
  xdg.configFile."DankMaterialShell/themes/stylix/theme.json".text = builtins.toJSON {
    id = "stylix";
    name = "Stylix Base16";
    version = "1.0.0";
    author = "nix-config";
    description = "Generated from Stylix Base16 colors with a single coherent Base16 palette";
    dark = base16Theme;
    # Base16 only gives us one coherent palette here. Reusing it is better than
    # fabricating a fake light theme from accent slots.
    light = base16Theme;
  };
}
